# Weather Data Analysis

- IN THIS POJECT WE WILL USE FOLLOWING COMMANDS/OPERATIONS TO ANALYZE THE WEATHER'S DATA :-

### Pandas

- Pandas :- Pandas is a library used to work with Data-Set.
- Pandas has Functions for Analyzing,Cleaning,Exploring & Manipulating data.

In [127]:
import pandas as pd

### NumPy

- NumPy :- NumPy library is used to perform Mathematical Operation on Arrays.

In [128]:
import numpy as np

### Importing the DataSet/DataFrame

- Syntax to Load or import the DataSet(DataFrame)
- d = pd.read_csv(r'csv_FilePath Or Location\csv_fileName')
- d is a variable where we have stored Whole Data Set/frame

In [129]:
d = pd.read_csv(r'A:\MTECH(Data Science)\DataSet\archive\weather.csv')

### NOW TO ANALYZE THE WEATHER'S DATA I AM USING FOLLOWING COMMANDS :-

# d

- This command will show whole Data-Set
- print(d) are eqivalent command.

In [130]:
d

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

# d.head()

- This command will show the by default first 5 rows from the loaded DataSet.

In [131]:
d.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No

# d.tail()

- This command will show the by default last 5 rows from the loaded DataSet.

In [132]:
d.tail()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

# d.head(8)

- This command will show the first N rows from the loaded DataSet.
- d.head(7) = This command will show the first 7 rows from the loaded DataSet.
- d.head(11) = This command will show the first 11 rows from the loaded DataSet.

In [133]:
d.head(8)

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
5,6.2,16.9,0.0,5.8,8.2,SE,44.0,SE,E,20.0,...,57,1023.8,1021.7,7,5,10.9,14.8,No,0.2,No
6,6.1,18.2,0.2,4.2,8.4,SE,43.0,SE,ESE,19.0,...,47,1024.6,1022.2,4,6,12.4,17.3,No,0.0,No
7,8.3,17.0,0.0,5.6,4.6,E,41.0,SE,E,11.0,...,57,1026.2,1024.2,6,7,12.1,15.5,No,0.0,No

# d.shape

- This command will show the Total No. of rows and Total No. of Columns of the loaded DataSet.

In [134]:
d.shape

(366, 22)

# d.index

- This command will show the Range of the loaded DataSet.

In [135]:
d.index

RangeIndex(start=0, stop=366, step=1)

# d.columns

- This command will show the complete Attributes(columns) of the loaded DataSet.

In [136]:
d.columns

Index(['MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine',
       'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RISK_MM', 'RainTomorrow'],
      dtype='object')

# d.dtypes

- This command will show the Data Type of each Column of the loaded DataSet.

In [137]:
d.dtypes

MinTemp          float64
MaxTemp          float64
Rainfall         float64
Evaporation      float64
Sunshine         float64
WindGustDir       object
WindGustSpeed    float64
WindDir9am        object
WindDir3pm        object
WindSpeed9am     float64
WindSpeed3pm       int64
Humidity9am        int64
Humidity3pm        int64
Pressure9am      float64
Pressure3pm      float64
Cloud9am           int64
Cloud3pm           int64
Temp9am          float64
Temp3pm          float64
RainToday         object
RISK_MM          float64
RainTomorrow      object
dtype: object

# d['Column_Name'].unique()

- This command will show all the unique values of a particular column and it can be apply in only single column.

In [138]:
d['MinTemp'].unique()

array([ 8. , 14. , 13.7, 13.3,  7.6,  6.2,  6.1,  8.3,  8.8,  8.4,  9.1,
        8.5, 10.1, 12.1, 12.4, 13.8, 11.7, 15.6, 15.3, 16.4, 12.8, 12. ,
       15.4, 12.9, 15.1, 13.6, 11.6, 16.6, 14.5, 16.3, 17.2, 16.5, 15. ,
       14.9, 11.8,  9.6,  8.9, 15.5, 10.8,  7.5, 12.6, 14.8, 19.9,  9.2,
       11.3,  9.8, 14.3, 14.4, 15.9, 16.7, 17.5, 14.7, 20.9, 17. , 16. ,
       17.9, 15.2, 10. ,  9.9, 10.3, 12.7, 13.2, 18. , 17.6, 17.1, 18.2,
       16.8, 10.4,  8.6, 11.2, 11.4, 11.5, 13. ,  7.7,  4.4,  7.4,  9.5,
       12.5, 13.9, 12.3, 13.1,  7.1,  4.2,  3.5,  5.3,  7. ,  0.4,  3.2,
        5.9,  8.1,  6.9,  5.6,  7.2,  5.4,  6.3,  7.9,  2.4,  2.5,  5. ,
        3.8,  4.3, -2.1, -1.8,  2.1,  0.5, -0.9, -0.2,  0.1,  1.5,  9.4,
        1.3,  2.2, -0.4,  4.5, -2.7,  0.3,  1.2, -0.3,  4.7,  4.9,  1.4,
       -0.1,  0.6,  4.6, 10.6,  7.8, 10.2,  7.3,  8.7,  1. ,  6.4,  4. ,
        0.9,  0.8, -1.5,  6.6, -1.6, -3.1, -0.6,  3. ,  2.9, -1.3,  1.8,
       -2.6,  2.7, -1.7, -1.1,  2.3, -2.2, -3.5, -1. , -2. , -2.3, -2.8,
       -1.9,  4.8,  3.1, -2.9,  3.7, -3.4, -5.3,  0. , -3.7, -3.3,  4.1,
        5.8,  0.2, -2.5, -0.5,  9. ,  3.9,  0.7,  1.1,  5.1,  6.5,  8.2,
        6.7, 11.9,  3.4,  3.3])

# d.nunique()

- This command will show total no. of in unique values in each column and it can be apply in single column as well as on whole DataFrame.
- d.nunique() Apply in whole DataFrame

In [139]:
d.nunique()

MinTemp          180
MaxTemp          187
Rainfall          47
Evaporation       55
Sunshine         114
WindGustDir       16
WindGustSpeed     35
WindDir9am        16
WindDir3pm        16
WindSpeed9am      22
WindSpeed3pm      26
Humidity9am       60
Humidity3pm       74
Pressure9am      190
Pressure3pm      193
Cloud9am           9
Cloud3pm           9
Temp9am          178
Temp3pm          200
RainToday          2
RISK_MM           47
RainTomorrow       2
dtype: int64

# d.nunique() Apply in Single DataFrame

- It will show Total No. of Unique values that are present in particular column(Attribute).

In [140]:
d['MinTemp'].nunique()

180

# d.value_counts

- This command will show all the unique values with their count(Times or frequency).
- It can be apply in only single column.

In [141]:
d['MinTemp'].value_counts()

0.5     6
4.4     6
15.1    5
3.2     5
2.3     5
       ..
13.9    1
9.5     1
7.7     1
11.4    1
3.3     1
Name: MinTemp, Length: 180, dtype: int64

In [142]:
d['RainTomorrow'].value_counts() # Show frequency

No     300
Yes     66
Name: RainTomorrow, dtype: int64

# d.info()

- This command will provide us basic information about the DataFrame.

In [143]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MinTemp        366 non-null    float64
 1   MaxTemp        366 non-null    float64
 2   Rainfall       366 non-null    float64
 3   Evaporation    366 non-null    float64
 4   Sunshine       363 non-null    float64
 5   WindGustDir    363 non-null    object
 6   WindGustSpeed  364 non-null    float64
 7   WindDir9am     335 non-null    object
 8   WindDir3pm     365 non-null    object
 9   WindSpeed9am   359 non-null    float64
 10  WindSpeed3pm   366 non-null    int64
 11  Humidity9am    366 non-null    int64
 12  Humidity3pm    366 non-null    int64
 13  Pressure9am    366 non-null    float64
 14  Pressure3pm    366 non-null    float64
 15  Cloud9am       366 non-null    int64
 16  Cloud3pm       366 non-null    int64
 17  Temp9am        366 non-null    float64
 18  Temp3pm        366 non-null    float64
 19  RainToday      366 non-null    object
 20  RISK_MM        366 non-null    float64
 21  RainTomorrow   366 non-null    object
dtypes: float64(12), int64(5), object(5)
memory usage: 63.0+ KB

# d.count

- This command will show total no. of Non-NULL values in each column and it can be apply in single column as well as on whole DataFrame.
- Apply in whole DataFrame

In [144]:
d.count()

MinTemp          366
MaxTemp          366
Rainfall         366
Evaporation      366
Sunshine         363
WindGustDir      363
WindGustSpeed    364
WindDir9am       335
WindDir3pm       365
WindSpeed9am     359
WindSpeed3pm     366
Humidity9am      366
Humidity3pm      366
Pressure9am      366
Pressure3pm      366
Cloud9am         366
Cloud3pm         366
Temp9am          366
Temp3pm          366
RainToday        366
RISK_MM          366
RainTomorrow     366
dtype: int64

# d.notnull().sum()

- This command is used to check all rows amd column are filled or not in our loaded dataframe.

In [145]:
d.notnull().sum()

MinTemp          366
MaxTemp          366
Rainfall         366
Evaporation      366
Sunshine         363
WindGustDir      363
WindGustSpeed    364
WindDir9am       335
WindDir3pm       365
WindSpeed9am     359
WindSpeed3pm     366
Humidity9am      366
Humidity3pm      366
Pressure9am      366
Pressure3pm      366
Cloud9am         366
Cloud3pm         366
Temp9am          366
Temp3pm          366
RainToday        366
RISK_MM          366
RainTomorrow     366
dtype: int64

# d.isnull().sum()

- This command is used to check NULL values present or not in our dataframe.
- isnull command is used to check for null values.

In [146]:
pd.isnull(d).sum()

MinTemp           0
MaxTemp           0
Rainfall          0
Evaporation       0
Sunshine          3
WindGustDir       3
WindGustSpeed     2
WindDir9am       31
WindDir3pm        1
WindSpeed9am      7
WindSpeed3pm      0
Humidity9am       0
Humidity3pm       0
Pressure9am       0
Pressure3pm       0
Cloud9am          0
Cloud3pm          0
Temp9am           0
Temp3pm           0
RainToday         0
RISK_MM           0
RainTomorrow      0
dtype: int64

### In this Data_Frame has NULL values so first of all we have to clean it and then we will apply any kind of operations.

- In above cell we have got null values in following columns :-

 Sunshine          3
 WindGustDir       3
 WindGustSpeed     2
 WindDir9am       31
 WindDir3pm        1
 WindSpeed9am      7

- So we have to remove null values by using drop command.

In [147]:
# drop null values
d.dropna(inplace=True)

# After removing null values.

In [148]:
pd.isnull(d).sum()

MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         0
WindGustDir      0
WindGustSpeed    0
WindDir9am       0
WindDir3pm       0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
RISK_MM          0
RainTomorrow     0
dtype: int64

# Operation - 1

Rename Column

In [149]:
# Syntax
# d.rename('columns={'Old_Name_Of_Column':'New_Name_Of_Column'})
# Rename Temporary
d.rename(columns={'WindGustDir':'WindGustDirection'})

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDirection,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [150]:
# Above Command Rename Temporary
d.head(2)

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes

In [151]:
# To Rename Permanently
# Syntax
# d.rename('columns={Old_Name_Of_Column':'New_Name_Of_Column'},inplace=True)
d.rename(columns={'WindGustDir':'WindGustDirection'},inplace=True) # Rename Permanently

In [152]:
# see again it is changed or not?
d.head(2)

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDirection,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes

# Operation - 2

Calculation of Mean

In [153]:
# Syntax
# d.Column_name.mean()
d.MinTemp.mean()

7.7429878048780525

In [154]:
d.MaxTemp.mean()

20.897560975609757

In [155]:
d.mean()

C:\Users\kumar\AppData\Local\Temp\ipykernel_14252\1214089992.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  d.mean()

MinTemp             7.742988
MaxTemp            20.897561
Rainfall            1.440854
Evaporation         4.702439
Sunshine            8.014939
WindGustSpeed      40.396341
WindSpeed9am       10.414634
WindSpeed3pm       18.185976
Humidity9am        71.100610
Humidity3pm        44.003049
Pressure9am      1019.350000
Pressure3pm      1016.530793
Cloud9am            3.905488
Cloud3pm            4.000000
Temp9am            12.815549
Temp3pm            19.556402
RISK_MM             1.422561
dtype: float64

In [156]:
d.groupby('MinTemp').mean()

,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RISK_MM
MinTemp,,,,,,,,,,,,,,,,
-5.3,13.10,0.0,2.2,7.90,33.0,4.0,20.0,94.0,47.0,1029.60,1025.60,6.0,6.0,0.10,12.2,0.0
-3.7,14.55,0.0,3.0,10.65,32.5,5.5,16.5,58.5,26.5,1028.40,1024.45,0.0,0.0,5.35,13.7,0.0
-3.5,9.40,0.2,2.0,6.20,38.0,18.0,17.5,84.0,58.0,1024.15,1021.85,4.5,5.5,3.45,7.6,0.2
-3.4,12.50,0.0,3.0,6.80,48.0,7.0,30.0,89.0,30.0,1025.20,1021.80,6.0,7.0,1.40,11.2,0.0
-3.1,12.00,0.0,1.8,3.90,35.0,4.0,13.0,80.0,52.0,1030.50,1030.00,1.0,6.0,5.90,10.2,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17.9,33.55,0.0,10.4,10.10,52.5,10.5,15.5,65.0,42.0,1012.95,1010.35,3.5,4.0,22.15,27.9,2.4
18.0,34.90,0.0,9.2,9.90,69.0,6.0,13.0,68.0,29.0,1018.00,1013.70,1.0,6.0,22.20,33.1,5.2
18.2,22.60,1.8,8.0,0.00,33.0,7.0,13.0,92.0,76.0,1014.40,1011.50,8.0,8.0,18.50,22.1,9.0
19.9,22.00,11.0,4.4,5.90,76.0,41.0,30.0,92.0,62.0,996.50,996.80,8.0,3.0,20.60,19.6,17.4
20.9,35.70,0.0,13.8,6.90,50.0,4.0,17.0,61.0,28.0,1007.60,1003.00,7.0,2.0,23.60,34.0,2.0

# Operation - 3

Calculation of Standard Deviation

In [157]:
# Syntax
# d.Column_name.std()
d.MinTemp.std()

5.945199248454697

In [158]:
d.MaxTemp.std()

6.7073099127283315

In [159]:
d.std()

C:\Users\kumar\AppData\Local\Temp\ipykernel_14252\4080983771.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  d.std()

MinTemp           5.945199
MaxTemp           6.707310
Rainfall          4.289427
Evaporation       2.681183
Sunshine          3.506646
WindGustSpeed    13.132176
WindSpeed9am      7.811544
WindSpeed3pm      8.926759
Humidity9am      12.983367
Humidity3pm      16.605975
Pressure9am       6.715244
Pressure3pm       6.469774
Cloud9am          2.974957
Cloud3pm          2.652101
Temp9am           5.542521
Temp3pm           6.644311
RISK_MM           4.234023
dtype: float64

# Operation - 4

Calculation of Variance

In [160]:
# Syntax
# d.Column_name.var()
d.MinTemp.var()

35.3453941038263

In [161]:
d.MaxTemp.var()

44.98800626538374

In [162]:
d.var()

C:\Users\kumar\AppData\Local\Temp\ipykernel_14252\3511739826.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  d.var()

MinTemp           35.345394
MaxTemp           44.988006
Rainfall          18.399182
Evaporation        7.188740
Sunshine          12.296565
WindGustSpeed    172.454054
WindSpeed9am      61.020213
WindSpeed3pm      79.687020
Humidity9am      168.567828
Humidity3pm      275.758400
Pressure9am       45.094495
Pressure3pm       41.857979
Cloud9am           8.850367
Cloud3pm           7.033639
Temp9am           30.719543
Temp3pm           44.146870
RISK_MM           17.926951
dtype: float64

# Operation - 5

Calculation of Median

In [163]:
# Syntax
# d.Column_name.median()
d.MinTemp.median()

7.9

In [164]:
d.MaxTemp.median()

20.4

In [165]:
d.median()

C:\Users\kumar\AppData\Local\Temp\ipykernel_14252\3286961719.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  d.median()

MinTemp             7.90
MaxTemp            20.40
Rainfall            0.00
Evaporation         4.40
Sunshine            8.75
WindGustSpeed      39.00
WindSpeed9am        7.00
WindSpeed3pm       17.00
Humidity9am        71.00
Humidity3pm        42.50
Pressure9am      1019.75
Pressure3pm      1016.90
Cloud9am            4.00
Cloud3pm            4.00
Temp9am            13.50
Temp3pm            18.85
RISK_MM             0.00
dtype: float64

# Operation - 6

Calculation of Mode

In [166]:
# Syntax
# d.Column_name.mode()
d.MinTemp.mode()

0    4.4
Name: MinTemp, dtype: float64

In [167]:
d.mode()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDirection,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,4.4,11.6,0.0,2.8,0.0,NW,39.0,SE,NW,6.0,...,34.0,1023.2,1019.3,1.0,1.0,14.0,11.1,No,0.0,No
1,NaN,14.7,NaN,NaN,8.4,NaN,NaN,NaN,NaN,NaN,...,NaN,1025.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,14.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,18.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Operation - 7

Calculation of Kurtosis

In [168]:
# Syntax
# d.Column_name.kurt()
# for single attribute
d.MinTemp.kurt()

-1.0678732874693733

In [169]:
# For complete attributers
d.kurt()

C:\Users\kumar\AppData\Local\Temp\ipykernel_14252\1413420561.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  d.kurt()

MinTemp          -1.067873
MaxTemp          -0.751754
Rainfall         27.611392
Evaporation      -0.216054
Sunshine         -0.266922
WindGustSpeed     1.594871
WindSpeed9am      1.535232
WindSpeed3pm      0.265588
Humidity9am      -0.145622
Humidity3pm      -0.118062
Pressure9am      -0.088998
Pressure3pm       0.000914
Cloud9am         -1.719883
Cloud3pm         -1.621962
Temp9am          -0.881008
Temp3pm          -0.670370
RISK_MM          28.557778
dtype: float64

# Operation - 8

Calculation of Skewness

In [170]:
# Syntax
# d.Column_name.skew()
d.MinTemp.skew()

-0.07365803681446856

In [171]:
# For complete attributers
d.skew()

C:\Users\kumar\AppData\Local\Temp\ipykernel_14252\3048699516.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  d.skew()

MinTemp         -0.073658
MaxTemp          0.297350
Rainfall         4.679845
Evaporation      0.598352
Sunshine        -0.737128
WindGustSpeed    0.891562
WindSpeed9am     1.430616
WindSpeed3pm     0.646106
Humidity9am     -0.091999
Humidity3pm      0.539732
Pressure9am     -0.331647
Pressure3pm     -0.267506
Cloud9am         0.078980
Cloud3pm         0.080163
Temp9am         -0.094301
Temp3pm          0.263944
RISK_MM          4.723079
dtype: float64

# Operation - 9

Calculation of Correlation

In [172]:
# Syntax
# d.corr()
d.corr()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RISK_MM
MinTemp,1.000000,0.745911,0.197339,0.634720,0.007730,0.190596,0.058319,-0.106321,-0.160781,-0.013897,-0.502352,-0.503255,0.211640,0.125914,0.910805,0.716051,0.251519
MaxTemp,0.745911,1.000000,-0.077263,0.673162,0.444863,0.070911,-0.296485,-0.219886,-0.325106,-0.520412,-0.268054,-0.367040,-0.187416,-0.144976,0.869609,0.988925,0.058638
Rainfall,0.197339,-0.077263,1.000000,-0.011767,-0.158062,0.099442,0.238705,0.058151,0.146321,0.287244,-0.348731,-0.263710,0.172610,0.134894,0.071893,-0.089740,0.101909
Evaporation,0.634720,0.673162,-0.011767,1.000000,0.310124,0.258050,0.006259,0.019594,-0.492218,-0.374532,-0.363936,-0.380702,-0.114261,-0.111387,0.688749,0.655896,0.099727
Sunshine,0.007730,0.444863,-0.158062,0.310124,1.000000,0.084768,-0.103841,0.046140,-0.501596,-0.760267,0.025630,-0.024120,-0.697603,-0.657198,0.199659,0.463721,-0.357231
WindGustSpeed,0.190596,0.070911,0.099442,0.258050,0.084768,1.000000,0.540717,0.687071,-0.338276,-0.043254,-0.524737,-0.510826,-0.018216,0.042849,0.229164,0.036039,0.269151
WindSpeed9am,0.058319,-0.296485,0.238705,0.006259,-0.103841,0.540717,1.000000,0.495946,-0.222337,0.202122,-0.344290,-0.233682,0.117625,-0.012990,-0.017843,-0.315906,0.053529
WindSpeed3pm,-0.106321,-0.219886,0.058151,0.019594,0.046140,0.687071,0.495946,1.000000,-0.260960,0.015860,-0.344889,-0.318008,-0.033882,0.011625,-0.057454,-0.239119,0.012931
Humidity9am,-0.160781,-0.325106,0.146321,-0.492218,-0.501596,-0.338276,-0.222337,-0.260960,1.000000,0.526695,0.102250,0.109549,0.417496,0.289618,-0.395647,-0.321299,0.157148
Humidity3pm,-0.013897,-0.520412,0.287244,-0.374532,-0.760267,-0.043254,0.202122,0.015860,0.526695,1.000000,-0.136289,-0.047607,0.565174,0.530715,-0.230820,-0.569348,0.323494
Pressure9am,-0.502352,-0.268054,-0.348731,-0.363936,0.025630,-0.524737,-0.344290,-0.344889,0.102250,-0.136289,1.000000,0.966744,-0.168316,-0.146196,-0.453669,-0.229817,-0.314815
Pressure3pm,-0.503255,-0.367040,-0.263710,-0.380702,-0.024120,-0.510826,-0.233682,-0.318008,0.109549,-0.047607,0.966744,1.000000,-0.132247,-0.146235,-0.496853,-0.332099,-0.336461
Cloud9am,0.211640,-0.187416,0.172610,-0.114261,-0.697603,-0.018216,0.117625,-0.033882,0.417496,0.565174,-0.168316,-0.132247,1.000000,0.528296,0.010012,-0.213509,0.268979
Cloud3pm,0.125914,-0.144976,0.134894,-0.111387,-0.657198,0.042849,-0.012990,0.011625,0.289618,0.530715,-0.146196,-0.146235,0.528296,1.000000,0.044542,-0.181667,0.311882
Temp9am,0.910805,0.869609,0.071893,0.688749,0.199659,0.229164,-0.017843,-0.057454,-0.395647,-0.230820,-0.453669,-0.496853,0.010012,0.044542,1.000000,0.843509,0.201508
Temp3pm,0.716051,0.988925,-0.089740,0.655896,0.463721,0.036039,-0.315906,-0.239119,-0.321299,-0.569348,-0.229817,-0.332099,-0.213509,-0.181667,0.843509,1.000000,0.028888
RISK_MM,0.251519,0.058638,0.101909,0.099727,-0.357231,0.269151,0.053529,0.012931,0.157148,0.323494,-0.314815,-0.336461,0.268979,0.311882,0.201508,0.028888,1.000000

# Operation - 10

FILTER

We are filtring the records where the attribute RainTomorrow has only Yes.

In [173]:
# Syntax
# d[d['Column_name']=='value']

d[d['RainTomorrow']=='Yes']

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDirection,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
8,8.8,19.5,0.0,4.0,4.1,S,48.0,E,ENE,19.0,...,48,1026.1,1022.7,7,7,14.1,18.9,No,16.2,Yes
16,13.8,31.2,0.0,7.2,8.4,ESE,44.0,WSW,W,6.0,...,23,1014.4,1009.8,7,6,20.2,29.8,No,1.2,Yes
21,16.4,19.4,0.4,9.2,0.0,E,26.0,ENE,E,6.0,...,72,1010.7,1008.9,8,8,16.5,18.3,No,25.8,Yes
29,13.6,24.1,0.4,2.6,0.5,NNW,30.0,SSW,S,6.0,...,49,1017.2,1013.3,8,7,17.3,23.2,No,22.6,Yes
30,15.1,20.4,22.6,2.4,0.2,SSE,41.0,E,S,6.0,...,90,1015.0,1014.1,8,8,17.0,16.3,Yes,4.2,Yes
32,16.6,24.2,0.2,6.6,4.7,NW,50.0,WNW,NW,13.0,...,60,1007.9,1004.6,7,7,20.5,19.9,No,6.6,Yes
36,17.2,25.8,0.0,4.2,8.8,SW,41.0,NW,N,6.0,...,74,1014.5,1011.5,6,7,21.5,22.6,No,4.0,Yes
44,10.1,29.9,0.0,6.8,8.8,E,41.0,SE,WNW,2.0,...,36,1012.6,1010.2,1,8,17.4,29.1,No,5.4,Yes
45,15.5,21.1,5.4,6.4,0.9,S,31.0,SSE,NE,6.0,...,86,1010.1,1008.6,8,8,16.6,20.0,Yes,1.4,Yes
48,12.8,21.0,0.0,6.4,0.8,NE,22.0,NE,ENE,7.0,...,54,1018.0,1015.6,8,8,16.1,20.0,No,3.4,Yes
49,12.6,23.1,3.4,1.6,2.3,NNW,30.0,N,NW,4.0,...,74,1015.8,1014.1,8,7,15.3,20.4,Yes,6.4,Yes
50,14.8,29.5,6.4,1.8,8.1,N,41.0,NW,NW,6.0,...,48,1012.9,1008.3,2,7,21.0,28.2,Yes,11.0,Yes
51,19.9,22.0,11.0,4.4,5.9,NNW,76.0,N,WNW,41.0,...,62,996.5,996.8,8,3,20.6,19.6,Yes,17.4,Yes
53,12.4,24.4,0.0,6.2,12.1,NW,44.0,NNW,WNW,7.0,...,43,1012.8,1009.7,6,4,15.0,22.5,No,3.4,Yes
56,14.3,26.7,0.0,7.2,7.1,NNW,65.0,N,NNW,7.0,...,64,1017.3,1014.3,7,7,19.8,19.0,No,14.4,Yes
72,20.9,35.7,0.0,13.8,6.9,SW,50.0,E,WNW,4.0,...,28,1007.6,1003.0,7,2,23.6,34.0,No,2.0,Yes
76,17.9,33.2,0.0,10.4,8.4,N,59.0,N,NNE,15.0,...,62,1008.5,1006.1,6,7,24.5,23.5,No,4.8,Yes
78,15.1,20.4,0.0,9.6,0.1,ESE,39.0,ESE,ESE,17.0,...,55,1017.5,1015.8,8,8,17.8,19.4,No,18.8,Yes
79,15.3,19.6,18.8,5.0,0.0,NE,33.0,SSE,NNE,9.0,...,88,1008.7,1006.0,8,8,18.0,18.6,Yes,12.2,Yes
90,18.0,34.9,0.0,9.2,9.9,NW,69.0,N,W,6.0,...,29,1018.0,1013.7,1,6,22.2,33.1,No,5.2,Yes
91,17.6,27.8,5.2,10.2,3.6,ESE,39.0,N,NNW,13.0,...,49,1014.6,1012.8,7,8,21.4,26.3,Yes,2.2,Yes
94,17.1,29.6,0.0,5.8,9.2,E,48.0,SE,ESE,9.0,...,38,1016.7,1012.8,6,7,21.7,29.1,No,1.8,Yes
95,18.2,22.6,1.8,8.0,0.0,ENE,33.0,SSE,ENE,7.0,...,76,1014.4,1011.5,8,8,18.5,22.1,Yes,9.0,Yes
98,14.5,24.2,0.0,6.8,5.9,SSW,61.0,N,NNW,11.0,...,76,999.4,998.9,7,7,17.9,20.3,No,16.2,Yes
102,8.9,26.0,0.0,5.0,10.7,NE,31.0,SE,NE,7.0,...,34,1016.1,1011.7,1,5,14.6,24.2,No,4.4,Yes
103,14.5,24.2,4.4,6.6,5.9,W,48.0,NNW,WNW,9.0,...,60,1010.8,1006.8,8,5,15.8,22.6,Yes,11.0,Yes
111,12.0,28.9,0.0,7.2,8.2,ESE,39.0,SSE,WNW,2.0,...,31,1012.2,1009.1,2,7,17.4,28.6,No,1.8,Yes
112,16.3,24.8,1.8,7.8,3.8,S,50.0,NNW,N,4.0,...,56,1011.8,1008.4,7,7,17.5,24.0,Yes,6.6,Yes
119,14.8,17.3,0.0,7.6,0.8,SSE,48.0,S,SE,13.0,...,78,1010.0,1009.9,7,7,15.7,15.3,No,10.4,Yes
144,15.5,22.4,0.6,4.8,1.9,NW,28.0,SSE,WNW,6.0,...,68,1018.7,1015.4,8,7,17.1,21.1,No,6.4,Yes
145,13.1,17.4,6.4,2.8,0.0,NNW,43.0,N,N,11.0,...,93,1010.2,1006.5,8,8,16.4,16.6,Yes,19.8,Yes
153,5.3,23.3,0.0,3.6,5.6,NNW,83.0,SSW,NW,2.0,...,26,1018.0,1010.5,1,8,9.5,22.5,No,2.6,Yes
163,6.1,24.1,0.0,4.6,6.1,WNW,35.0,SSW,WNW,6.0,...,32,1019.2,1015.8,7,3,11.5,23.7,No,2.0,Yes
164,7.1,19.8,2.0,3.2,7.7,W,39.0,SSE,NW,13.0,...,56,1018.4,1013.8,5,2,10.7,19.1,Yes,5.2,Yes
178,7.9,18.7,0.0,5.8,5.8,NW,59.0,NNW,NW,26.0,...,51,1003.2,997.7,6,6,14.4,16.6,No,7.2,Yes
196,-0.4,17.9,0.0,2.4,8.7,NW,33.0,NNE,NW,2.0,...,40,1023.5,1018.7,1,2,6.8,17.7,No,1.8,Yes
206,-0.3,17.5,0.0,1.6,8.4,W,39.0,SE,NNW,6.0,...,48,1025.5,1021.8,1,5,6.2,17.2,No,3.8,Yes
207,4.7,18.5,3.8,2.0,5.1,ESE,22.0,NNW,W,6.0,...,50,1026.6,1023.1,7,4,7.0,17.9,Yes,5.2,Yes
215,9.8,14.4,0.8,0.6,0.0,ESE,20.0,S,ESE,9.0,...,86,1028.5,1027.2,8,8,12.1,13.6,No,3.8,Yes
231,4.0,15.9,0.0,0.6,2.0,NNW,17.0,SE,SSE,6.0,...,63,1022.5,1019.7,8,7,8.4,14.8,No,4.8,Yes
242,0.5,15.4,0.0,2.4,6.4,W,70.0,NW,NNW,22.0,...,68,1017.2,1010.2,1,7,9.7,12.9,No,2.0,Yes
252,1.8,8.7,0.0,1.8,1.2,NW,65.0,NW,NW,31.0,...,85,1014.6,1010.5,7,7,6.0,6.9,No,1.6,Yes
260,1.3,10.6,0.0,0.8,5.6,NW,46.0,NNW,WNW,24.0,...,73,1010.8,1009.4,3,5,7.7,8.2,No,1.2,Yes
269,-2.3,9.7,0.0,1.4,1.9,SSE,28.0,SSE,WSW,6.0,...,66,1013.8,1010.0,7,7,1.0,7.8,No,1.4,Yes
274,3.0,9.7,1.0,2.6,0.7,W,65.0,NW,NW,19.0,...,82,1005.1,1001.3,8,7,9.6,8.6,No,6.6,Yes
280,-0.6,11.1,0.0,3.0,5.0,NNW,41.0,SE,N,7.0,...,78,1018.4,1015.9,7,7,3.8,5.7,No,1.2,Yes
303,0.5,16.3,0.0,1.8,4.1,NNW,39.0,SSW,WSW,4.0,...,45,1023.7,1017.5,7,8,6.2,15.4,No,4.0,Yes
304,6.1,17.2,4.0,2.2,2.4,NW,59.0,NW,WNW,24.0,...,85,1011.2,1010.4,7,7,13.5,12.6,Yes,7.4,Yes
317,9.0,25.5,0.0,5.6,10.2,NW,50.0,N,NW,20.0,...,31,1015.3,1011.4,3,1,17.5,25.1,No,9.8,Yes
318,13.1,19.4,9.8,8.8,6.0,NNW,67.0,N,NW,39.0,...,43,1007.3,1006.0,7,1,16.7,18.2,Yes,1.6,Yes
319,8.7,19.7,1.6,5.2,8.0,NW,98.0,NW,NNW,31.0,...,33,1009.1,1001.5,3,6,15.6,18.5,Yes,3.4,Yes
326,3.2,21.9,0.0,6.8,5.2,NW,80.0,SSE,NW,2.0,...,50,1012.1,1006.5,1,8,15.9,21.0,No,17.4,Yes
337,16.8,28.9,0.0,10.0,10.8,NNW,70.0,NW,NW,31.0,...,22,1016.3,1011.8,1,1,22.5,28.4,No,7.6,Yes
338,14.4,20.7,7.6,9.4,4.9,NNW,33.0,NNW,NNW,20.0,...,65,1015.5,1013.2,8,4,14.5,19.3,Yes,3.0,Yes
340,11.2,18.0,0.0,4.8,8.4,W,65.0,N,W,24.0,...,40,1009.5,1005.3,5,4,12.8,16.2,No,8.2,Yes
347,6.7,26.1,0.0,6.2,7.5,SSW,70.0,NE,NNW,6.0,...,47,1020.9,1016.0,4,7,16.3,23.2,No,13.2,Yes

# Operation - 11

FILTER

We are filtring the records where the attribute RainTomorrow has only No.

In [174]:
d[d['RainTomorrow']=='No']

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDirection,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
5,6.2,16.9,0.0,5.8,8.2,SE,44.0,SE,E,20.0,...,57,1023.8,1021.7,7,5,10.9,14.8,No,0.2,No
6,6.1,18.2,0.2,4.2,8.4,SE,43.0,SE,ESE,19.0,...,47,1024.6,1022.2,4,6,12.4,17.3,No,0.0,No
7,8.3,17.0,0.0,5.6,4.6,E,41.0,SE,E,11.0,...,57,1026.2,1024.2,6,7,12.1,15.5,No,0.0,No
9,8.4,22.8,16.2,5.4,7.7,E,31.0,S,ESE,7.0,...,32,1024.1,1020.7,7,1,13.3,21.7,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

# Operation - 12

Calculation of Minimum Value

In [175]:
# This command will give us minimum value from each column.
d.min()

MinTemp               -5.3
MaxTemp                7.6
Rainfall               0.0
Evaporation            0.2
Sunshine               0.0
WindGustDirection        E
WindGustSpeed         13.0
WindDir9am               E
WindDir3pm               E
WindSpeed9am           2.0
WindSpeed3pm             4
Humidity9am             36
Humidity3pm             13
Pressure9am          996.5
Pressure3pm          996.8
Cloud9am                 0
Cloud3pm                 0
Temp9am                0.1
Temp3pm                5.1
RainToday               No
RISK_MM                0.0
RainTomorrow            No
dtype: object

In [176]:
# For Particular column
d['RISK_MM'].min()

0.0

In [177]:
d.groupby('MinTemp').min()

,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDirection,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
MinTemp,,,,,,,,,,,,,,,,,,,,,
-5.3,13.1,0.0,2.2,7.9,NW,33.0,N,NNW,4.0,20,...,47,1029.6,1025.6,6,6,0.1,12.2,No,0.0,No
-3.7,14.4,0.0,2.6,10.4,NNW,22.0,N,N,2.0,11,...,25,1025.8,1020.9,0,0,5.2,13.4,No,0.0,No
-3.5,7.6,0.0,1.6,4.7,ESE,26.0,N,ESE,6.0,11,...,48,1014.8,1012.6,1,5,3.3,5.1,No,0.0,No
-3.4,12.5,0.0,3.0,6.8,SSE,48.0,NNW,WNW,7.0,30,...,30,1025.2,1021.8,6,7,1.4,11.2,No,0.0,No
-3.1,12.0,0.0,1.8,3.9,ESE,35.0,SSW,NE,4.0,13,...,52,1030.5,1030.0,1,6,5.9,10.2,No,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17.9,33.2,0.0,10.4,8.4,ENE,46.0,N,NNE,6.0,11,...,22,1008.5,1006.1,1,1,19.8,23.5,No,0.0,No
18.0,34.9,0.0,9.2,9.9,NW,69.0,N,W,6.0,13,...,29,1018.0,1013.7,1,6,22.2,33.1,No,5.2,Yes
18.2,22.6,1.8,8.0,0.0,ENE,33.0,SSE,ENE,7.0,13,...,76,1014.4,1011.5,8,8,18.5,22.1,Yes,9.0,Yes
19.9,22.0,11.0,4.4,5.9,NNW,76.0,N,WNW,41.0,30,...,62,996.5,996.8,8,3,20.6,19.6,Yes,17.4,Yes
20.9,35.7,0.0,13.8,6.9,SW,50.0,E,WNW,4.0,17,...,28,1007.6,1003.0,7,2,23.6,34.0,No,2.0,Yes

# d.sum()

In [178]:
d.sum()

MinTemp                                                         2539.7
MaxTemp                                                         6854.4
Rainfall                                                         472.6
Evaporation                                                     1542.4
Sunshine                                                        2628.9
WindGustDirection    NWENENWNWSSESESEESENEWNWNWNWEESESENEWNWEESENNE...
WindGustSpeed                                                  13250.0
WindDir9am           SWENWNWSSESESESEESSEESWNWSSEWSWSWNNENNWNENESWS...
WindDir3pm           NWWNNEWESEEESEEENEESENWNWNWWWWSWWNEWNNWNWESENE...
WindSpeed9am                                                    3416.0
WindSpeed3pm                                                      5965
Humidity9am                                                      23321
Humidity3pm                                                      14433
Pressure9am                                                   334346.8
Pressure3pm                                                   333422.1
Cloud9am                                                          1281
Cloud3pm                                                          1312
Temp9am                                                         4203.5
Temp3pm                                                         6414.5
RainToday            NoYesYesYesYesNoNoNoNoYesNoNoNoNoNoNoNoYesNoNo...
RISK_MM                                                          466.6
RainTomorrow         YesYesYesYesNoNoNoNoYesNoNoNoNoNoNoNoYesNoNoNo...
dtype: object

# d.describe()

- This command will show us count, mean, std, min, max of whole dataframe.

In [179]:
d.describe()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RISK_MM
count,328.000000,328.000000,328.000000,328.000000,328.000000,328.000000,328.000000,328.000000,328.000000,328.000000,328.000000,328.000000,328.000000,328.000000,328.000000,328.000000,328.000000
mean,7.742988,20.897561,1.440854,4.702439,8.014939,40.396341,10.414634,18.185976,71.100610,44.003049,1019.350000,1016.530793,3.905488,4.000000,12.815549,19.556402,1.422561
std,5.945199,6.707310,4.289427,2.681183,3.506646,13.132176,7.811544,8.926759,12.983367,16.605975,6.715244,6.469774,2.974957,2.652101,5.542521,6.644311,4.234023
min,-5.300000,7.600000,0.000000,0.200000,0.000000,13.000000,2.000000,4.000000,36.000000,13.000000,996.500000,996.800000,0.000000,0.000000,0.100000,5.100000,0.000000
25%,2.850000,15.500000,0.000000,2.550000,6.000000,31.000000,6.000000,11.000000,63.000000,32.000000,1014.800000,1012.400000,1.000000,1.000000,8.175000,14.500000,0.000000
50%,7.900000,20.400000,0.000000,4.400000,8.750000,39.000000,7.000000,17.000000,71.000000,42.500000,1019.750000,1016.900000,4.000000,4.000000,13.500000,18.850000,0.000000
75%,12.800000,25.800000,0.200000,6.600000,10.700000,46.000000,13.000000,24.000000,80.000000,54.000000,1024.300000,1021.125000,7.000000,7.000000,17.200000,24.225000,0.200000
max,20.900000,35.800000,39.800000,13.800000,13.600000,98.000000,41.000000,52.000000,99.000000,93.000000,1035.700000,1033.200000,8.000000,8.000000,24.700000,34.500000,39.800000

# Operation - 13

Calculation of Maximum Value

In [180]:
# This command will give us maximum value from each column.
d.max()

MinTemp                20.9
MaxTemp                35.8
Rainfall               39.8
Evaporation            13.8
Sunshine               13.6
WindGustDirection       WSW
WindGustSpeed          98.0
WindDir9am              WSW
WindDir3pm              WSW
WindSpeed9am           41.0
WindSpeed3pm             52
Humidity9am              99
Humidity3pm              93
Pressure9am          1035.7
Pressure3pm          1033.2
Cloud9am                  8
Cloud3pm                  8
Temp9am                24.7
Temp3pm                34.5
RainToday               Yes
RISK_MM                39.8
RainTomorrow            Yes
dtype: object

In [181]:
# For Particular column
d['RISK_MM'].max()

39.8

In [182]:
d.groupby('MinTemp').max()

,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDirection,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
MinTemp,,,,,,,,,,,,,,,,,,,,,
-5.3,13.1,0.0,2.2,7.9,NW,33.0,N,NNW,4.0,20,...,47,1029.6,1025.6,6,6,0.1,12.2,No,0.0,No
-3.7,14.7,0.0,3.4,10.9,SSE,43.0,SE,NNW,9.0,22,...,28,1031.0,1028.0,0,0,5.5,14.0,No,0.0,No
-3.5,11.2,0.4,2.4,7.7,NW,50.0,NW,NW,30.0,24,...,68,1033.5,1031.1,8,6,3.6,10.1,No,0.4,No
-3.4,12.5,0.0,3.0,6.8,SSE,48.0,NNW,WNW,7.0,30,...,30,1025.2,1021.8,6,7,1.4,11.2,No,0.0,No
-3.1,12.0,0.0,1.8,3.9,ESE,35.0,SSW,NE,4.0,13,...,52,1030.5,1030.0,1,6,5.9,10.2,No,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17.9,33.9,0.0,10.4,11.8,N,59.0,S,W,15.0,20,...,62,1017.4,1014.6,6,7,24.5,32.3,No,4.8,Yes
18.0,34.9,0.0,9.2,9.9,NW,69.0,N,W,6.0,13,...,29,1018.0,1013.7,1,6,22.2,33.1,No,5.2,Yes
18.2,22.6,1.8,8.0,0.0,ENE,33.0,SSE,ENE,7.0,13,...,76,1014.4,1011.5,8,8,18.5,22.1,Yes,9.0,Yes
19.9,22.0,11.0,4.4,5.9,NNW,76.0,N,WNW,41.0,30,...,62,996.5,996.8,8,3,20.6,19.6,Yes,17.4,Yes
20.9,35.7,0.0,13.8,6.9,SW,50.0,E,WNW,4.0,17,...,28,1007.6,1003.0,7,2,23.6,34.0,No,2.0,Yes

# Operation - 14

str.contains

# Retrieved data only if RainToday is Yes

In [183]:
d[(d['RainToday'].str.contains('Yes'))]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDirection,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
9,8.4,22.8,16.2,5.4,7.7,E,31.0,S,ESE,7.0,...,32,1024.1,1020.7,7,1,13.3,21.7,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,3.9,13.2,3.4,6.6,11.0,WNW,65.0,WNW,WNW,26.0,...,33,1017.0,1017.6,3,1,7.1,12.2,Yes,0.0,No
327,7.8,16.2,17.4,6.4,7.9,NW,50.0,NW,N,15.0,...,44,1016.7,1017.8,7,1,8.0,14.3,Yes,0.0,No
338,14.4,20.7,7.6,9.4,4.9,NNW,33.0,NNW,NNW,20.0,...,65,1015.5,1013.2,8,4,14.5,19.3,Yes,3.0,Yes
339,10.3,21.3,3.0,4.2,6.7,NNW,43.0,ENE,N,7.0,...,46,1018.1,1013.6,8,1,11.7,19.8,Yes,0.0,No
341,0.3,16.0,8.2,5.4,11.8,NW,57.0,NNW,N,11.0,...,45,1016.8,1013.3,1,1,6.9,14.6,Yes,0.0,No

In [184]:
d[d['RainToday']=='Yes']

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDirection,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
9,8.4,22.8,16.2,5.4,7.7,E,31.0,S,ESE,7.0,...,32,1024.1,1020.7,7,1,13.3,21.7,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,3.9,13.2,3.4,6.6,11.0,WNW,65.0,WNW,WNW,26.0,...,33,1017.0,1017.6,3,1,7.1,12.2,Yes,0.0,No
327,7.8,16.2,17.4,6.4,7.9,NW,50.0,NW,N,15.0,...,44,1016.7,1017.8,7,1,8.0,14.3,Yes,0.0,No
338,14.4,20.7,7.6,9.4,4.9,NNW,33.0,NNW,NNW,20.0,...,65,1015.5,1013.2,8,4,14.5,19.3,Yes,3.0,Yes
339,10.3,21.3,3.0,4.2,6.7,NNW,43.0,ENE,N,7.0,...,46,1018.1,1013.6,8,1,11.7,19.8,Yes,0.0,No
341,0.3,16.0,8.2,5.4,11.8,NW,57.0,NNW,N,11.0,...,45,1016.8,1013.3,1,1,6.9,14.6,Yes,0.0,No

# Operation - 15

In [185]:
d[d['RainToday']=='No']

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDirection,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
5,6.2,16.9,0.0,5.8,8.2,SE,44.0,SE,E,20.0,...,57,1023.8,1021.7,7,5,10.9,14.8,No,0.2,No
6,6.1,18.2,0.2,4.2,8.4,SE,43.0,SE,ESE,19.0,...,47,1024.6,1022.2,4,6,12.4,17.3,No,0.0,No
7,8.3,17.0,0.0,5.6,4.6,E,41.0,SE,E,11.0,...,57,1026.2,1024.2,6,7,12.1,15.5,No,0.0,No
8,8.8,19.5,0.0,4.0,4.1,S,48.0,E,ENE,19.0,...,48,1026.1,1022.7,7,7,14.1,18.9,No,16.2,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

# If 'RainToday =='No' AND 'Rainfall'==0.0 AND 'RISK_MM'==0.0 Then It May be No Rain Tomorrow

In [186]:
d[(d['RainToday']=='No')&(d['Rainfall']==0.0)&(d['RISK_MM']==0.0)]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDirection,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
7,8.3,17.0,0.0,5.6,4.6,E,41.0,SE,E,11.0,...,57,1026.2,1024.2,6,7,12.1,15.5,No,0.0,No
12,10.1,27.9,0.0,7.2,13.0,WNW,30.0,S,NW,6.0,...,29,1022.0,1017.1,0,1,17.0,27.1,No,0.0,No
13,12.1,30.9,0.0,6.2,12.4,NW,44.0,WNW,W,7.0,...,20,1017.3,1013.1,1,4,19.7,30.7,No,0.0,No
14,10.1,31.2,0.0,8.8,13.1,NW,41.0,S,W,6.0,...,16,1018.2,1013.7,0,1,18.7,30.4,No,0.0,No
15,12.4,32.1,0.0,8.4,11.1,E,46.0,SE,WSW,7.0,...,22,1017.9,1012.8,0,3,19.1,30.7,No,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [187]:
d[(d['RainToday']=='Yes')&(d['Rainfall']!=0.0)]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDirection,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
9,8.4,22.8,16.2,5.4,7.7,E,31.0,S,ESE,7.0,...,32,1024.1,1020.7,7,1,13.3,21.7,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,3.9,13.2,3.4,6.6,11.0,WNW,65.0,WNW,WNW,26.0,...,33,1017.0,1017.6,3,1,7.1,12.2,Yes,0.0,No
327,7.8,16.2,17.4,6.4,7.9,NW,50.0,NW,N,15.0,...,44,1016.7,1017.8,7,1,8.0,14.3,Yes,0.0,No
338,14.4,20.7,7.6,9.4,4.9,NNW,33.0,NNW,NNW,20.0,...,65,1015.5,1013.2,8,4,14.5,19.3,Yes,3.0,Yes
339,10.3,21.3,3.0,4.2,6.7,NNW,43.0,ENE,N,7.0,...,46,1018.1,1013.6,8,1,11.7,19.8,Yes,0.0,No
341,0.3,16.0,8.2,5.4,11.8,NW,57.0,NNW,N,11.0,...,45,1016.8,1013.3,1,1,6.9,14.6,Yes,0.0,No

### In this Weather Data Analysis we apply Following Algoriths for Weather prediction :-
 - Decision Tree
 - NBC
 - SVM
 - ARIMA

### I have completed this projet with the help of online resourses and plateform.

- Name - Aatish Kumar Baitha
- M.Tech(Data Science 2nd Year Student)

### My Linkedin Profile -
- www.linkedin.com/in/aatish-kumar-baitha-ba9523191

### My Blog -
- https://computersciencedatascience.blogspot.com/

### Thank you!